name: kaitai_compress

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build all Docker images
        run: |
          cd _test/docker
          ./build-images

      - name: Test on javascript/nodejs14
        run: |
          cd _test/docker
          ./dockerci javascript/nodejs14

      - name: Test on python/3.6
        run: |
          cd _test/docker
          ./dockerci python/3.6

      - name: Test on ruby/2.5
        run: |
          cd _test/docker
          ./dockerci ruby/2.5
