name: kaitai_compress

on: [push]

jobs:
  base_container_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install kaitai-struct-compiler
        run: |
          sudo apt-get update
          curl -fsSL -O https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.9/kaitai-struct-compiler_0.9_all.deb
          sudo apt-get install ./kaitai-struct-compiler_0.9_all.deb
          ksc --version
      - name: Compile ksy into target languages
        run: |
          cd _test
          ./compile-ksy
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: _test/docker/base/ubuntu_18.04
          file: _test/docker/base/ubuntu_18.04/Dockerfile
          tags: name/kaitai-compress-test-base-ubuntu_18.04:latest
          outputs: type=oci,dest=/tmp/kaitai-compress-test-base-ubuntu_18.04.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kaitai-compress-test-base-ubuntu_18.04
          path: /tmp/kaitai-compress-test-base-ubuntu_18.04.tar
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build all Docker images
        run: |
          cd _test/docker
          DOCKER_ENGINE=docker ./build-images

      - name: Test on javascript/nodejs14
        run: |
          cd _test/docker
          DOCKER_ENGINE=docker ./dockerci javascript/nodejs14

      - name: Test on python/3.6
        run: |
          cd _test/docker
          DOCKER_ENGINE=docker ./dockerci python/3.6

      - name: Test on ruby/2.5
        run: |
          cd _test/docker
          DOCKER_ENGINE=docker ./dockerci ruby/2.5
